# Introduction and Background

Binge-watching has been around for almost two decades, having been popularized by the availability (and accessibility) of TV shows like *Grey’s Anatomy* and *Breaking Bad* on streaming platforms like Netflix, Hulu, and Amazon Prime Video starting in the mid- to late 2000s. However, it really took off in 2013 when Netflix began releasing original content, starting with *House of Cards* and followed later that year by *Orange is the New Black*. Netflix started the practice of releasing all episodes of a season at once, a sharp departure from the standard weekly episodes. They continue to release most of their content this way, with a few exceptions (*Love is Blind* and season 3 of *Bridgerton*, notably). The public seemed to love it because they could watch at their own pace and didn’t have to wait a week after a mid-season cliff-hanger.

Shows like *Succession*, *The Last of Us*, and *The White Lotus*, all of which aired weekly on HBO at the same time they were released on HBO Max (later Max), created intense online discourse and reignited appointment television for an hour each Sunday. This provided not only a way for viewers to connect with each other, but also built momentum and caused the shows to stay in the public discourse for as many weeks as they aired.

As more streaming platforms came onto the market, so did more methods of releasing original content. While some shows are still released all at once (the “binge model”), many are released weekly, with some providing two or three episodes to start before transitioning to one episode a week. Some shows will also be released in batches of two episodes every week. For example, all 3 seasons of The Bear on Hulu have been released all at once, while season 1 of Shogun premiered with the first two episodes at once and then weekly.

With the rise of social media, platforms like Twitter became an important place to discuss TV shows with fellow viewers and get recommendations, later followed by TikTok. This project will seek to answer the question “*Does the release schedule of a show (weekly, in parts, or all at once) impact their staying power?*” Of particular interest is how shows perform on weekly Nielsen charts - both overall and by streaming platform - and their interest over time on Google Trends.

## Hypotheses 

In thinking about our question of what makes a show sustain its popularity, we propose the following hypotheses. First, releasing a show weekly will lead to more sustained popularity than releasing episodes all at once. Second, we hypothesize that drama shows will sustain their popularity longer than comedy shows, which can often be used for comfort watching (vs. drama shows being used for ‘active watching’). Along the same lines, we hypothesize that docuseries do better when they’re released all at once, likely due to the small number of episodes and often time-sensitive nature.