# Methods

In order to answer our question of interest, we had to gather a large amount of data from a wide number of various sources and databases. Unless mentioned otherwise, all of the data that was collected was data specifically about the US. Google Trends data and the ratings data all reflect the United States ratings and values; we decided to exclude worldwide ratings as we are most interested in the US Market.

### Google Trends

Google Trends data was gathered for each show, movie, or special that appeared on any of the ratings lists that were collected. This data was gathered for a timeframe of the last 5 years for each show, regardless of when the show premiered, in order to keep our data consistent. The data for each show was downloaded in a CSV file from the Google Trends website, with two columns: Date and Rating. This data manually was gathered manually because no API exists for the Google Trends data. The ratings are on a normalized scale, where 100 is equal to the point in time that the term was searched for most often, and 0 means that the term was not searched enough to crack the threshold.

The main issue to overcome was in getting the ratings associated with the show, as the show's title was not included in the CSV file. This was solved by naming each CSV file after the show or movie, and then adding a column of the file name so that we can match the ratings with the show titles.

In order to process such large quantities of CSV files, we organized them into folders based on the shows’ streaming platform. For example, the ‘Netflix’ folder contained the Google Trends CSVs for the shows *Stranger Things*, *Bridgerton*, and *The Crown*, among others. We then set up a function in R to loop over the folders of CSVs, which ingested all of the data, added the show’s name to the dataset as a new column, and then combined all rows together. Therefore, we were left with a single CSV of Google Trends data instead of hundreds of individual CSVs.

### Nielsen Weekly Streaming Ratings

Nielsen weekly steaming ratings (see current week [here](https://www.nielsen.com/data-center/top-ten/)) data was collected for as far back as they go, which is September 2020. Nielsen’s website only offers the most recent release, with no archive, so they were gathered from Variety articles ([example](https://variety.com/2024/tv/news/nielsen-top-10-ratings-streaming-1235693657/)) or the TV Grim Reaper on Twitter/X ([example](https://x.com/TVGrimReaper/status/1751995525032034443)). We specifically gathered the Top 10 data for Original Content; as we are mainly interested in how a streaming show’s release schedule influences its popularity, information on acquired shows that were released in other means was not information that we were interested in.

The biggest challenge that we encountered in processing the Nielsen Weekly Streaming data came from the form that the data was collected in. We were unable to find a CSV download for the Nielsen data (that we wouldn’t have to pay for), so we took screenshots of the Nielsen Top 10 Weekly data. Each screenshot contained the following information: the week that the ratings were from, show rank (1-10), the show’s name, the show’s SVOD Provider (streaming platform), the total number of episodes of the show, and the number of minutes that the program was watched in the past week.

As we had over 190 screenshots of Nielsen data, we did not wish to process this data manually. As such, we looked for ways to process these screenshots using programmatic means. A few APIs were tested to determine which could process the data the most successfully, with AWS being the best. All the images were fed through the Amazon Textract tool and downloaded as ZIP files, which contained a CSV. R was used to unzip the folders, clean the data, and merge the files together into a single CSV file. This CSV contained all of the weekly Nielsen data that was collected, with a column for the date of the rankings in order to keep each week separate.

### TV Grim Reaper Weekly Streaming Ratings

In addition to Nielsen’s overall ratings that encompass all of the major streaming platforms, Nielsen also releases weekly top 10 ratings for each streaming platform. The Nielsen top 10 lists for individual streaming platforms came from the TV Grim Reaper on Twitter/X ([example](https://x.com/TVGrimReaper/status/1787594943994941612)). The account is run by Bill Gorman, the co-founder of TV by the Numbers. He got the lists from a source who works at a company that subscribes to Nielsen. The TV Grim Reaper posted these screenshots starting from around June 2023 to April of 2024, so we have roughly one year’s worth of data to work with.

In total, we gathered ratings for the following platforms: Amazon Prime Video, Apple TV+, Disney+ and Hulu. We did not gather data for Netflix (see next section), and did not gather data for Peacock or Paramount+ as these platforms’ top 10 data was not captured by the TV Grim Reaper and we were unable to find any alternative means of collecting this data.

Screenshots were taken of each tweet, and like the Nielsen weekly ratings, were then fed through the Amazon Textract API from AWS. R was again used to unzip the folders, clean the data, and merge the files together (one for each platform).

### Netflix Weekly Top 10 Streaming Ratings

We did not gather Netflix Top 10 data from the TV Grim Reaper because Netflix is the only streaming platform that offers a CSV download ([link](https://www.netflix.com/tudum/top10/united-states/tv?week=2024-07-21)) of its entire Weekly Top 10 history (starting from August 2021 - present day). This was very beneficial to us, as it not only covered a longer period of time than the TV Grim Reaper ratings did, but it also came in a CSV download with all of the key variables and information that we were interested in, such as date, ranking, and show name.

Netflix's weekly top 10 ratings include the ratings for each individual country where Netflix is available. As such, we needed to filter the dataset to only include the ratings for the United States, our country of interest. Additionally, the top 10 download includes both top 10 ratings for movies and television shows, so we had to filter out any movies from the dataset. 

### FlixPatrol Yearly Streaming Ratings

FlixPatrol is a movie and TV ratings compiler that provides an API to get lists of ratings, with options to filter by show type, streaming platform, countries, years, and many more options. We gathered the yearly ratings for the eight main streaming platforms that we are analyzing (Amazon Prime, Apple TV, Disney+, HBO Max, Hulu, Netflix, Paramount+, Peacock) for the years of 2021-2024 (which overlaps with our weekly streaming ratings data). These ratings are calculated by the total number of minute that the show was watched over the year. We had no real issues getting these into a good format as the API allowed for specifying which columns we were interested in (show, platform, rating, and date), and offered CSV downloads of our queries.

One issue that we had with the FlixPatrol platform was in getting top 10 data for original programming only. The API had filters to only include shows from a specific creator, but not all streaming platforms were available as filters. In order to get around this, we got the overall top 10 lists for the streamers who didn’t appear as filters (Peacock and Paramount+), and then went through the lists manually to determine if the show was original programming or not. We went through the lists starting with the top until we had 10 original shows per year.

### Show Release Information

One of the main components of our project involves the release schedule of individual shows. To obtain this information, we compiled a list of all the shows we had data for, and using Wikipedia articles for each platform ([example](https://en.wikipedia.org/wiki/List_of_Amazon_Prime_Video_original_programming)), got the number of seasons for each show, as well as the release schedule for each season.

We binned the releases into three separate categories: all at once, hybrid, and weekly. All at once shows were shows whose entire seasons were released all at the same time. Weekly shows were shows whose episodes were released at a rate of one per week. Hybrid shows were shows whose episodes were released in some combination of all at once and weekly. A good example of this is the first season of Ted Lasso. The first three episodes were released all at once, and then the rest of the season was released at a rate of one episode per week.

We had to organize the show release by season because there are some shows, such as *Bridgerton*, whose release schedule changed over the course of the show’s lifetime. Seasons 1 and 2 of *Bridgerton* both released their entire seasons all at once, whereas Season 3 of *Bridgerton* released in two four-episode batches. As such, it would be misleading to classify *Bridgerton* as either a strictly ‘all at once’ or strictly ‘hybrid’ release schedule. Therefore, we decided to include each individual season to account for these scenarios of release format changes.

An argument can be made that Wikipedia’s information could be inaccurate. However, it was the only source that we could find that contained the release information for each individual episode of a show, whereas other sources would only contain when the season was released. Meaning, these sources would not tell us if a show was released weekly, all at once, or in a hybrid format. Furthermore, Wikipedia's community of editors actively works to correct errors and ensure accuracy, especially within heavily trafficked articles such as popular TV shows. As such, after weighing the pros and cons, we decided we were comfortable with the potential risks of inaccuracy and decided to proceed with Wikipedia as a source of reliable information.

We additionally gathered whether the show was original content to the streaming platform or acquired content from a third party source. A third-party source in this context would be whatever studio created and released the show. For example, *Young Sheldon* is on Netflix, but was created by and aired on CBS. Therefore, CBS is the third-party source for *Young Sheldon*. As we are most interested in the release schedule of streaming shows, acquired shows’ release schedules did not pertain to our questions of interest and as such, we excluded these shows from our analysis.

### Show Genre and Language Information

Another variable we were interested in was the genre of a show, and how the show’s genre can affect its popularity. To gather this information, we once again turned to Wikipedia. The show genres that are listed on Wikipedia can be extremely specific, such as the genre for the Amazon Prime Video show Gen V being listed as ‘superhero teen drama’. As one can imagine, that was the only show in the entire dataset that had that specific genre. Therefore, we knew that using the genres as they were listed on Wikipedia would not be sufficient for our needs and decided to bin the genres into their main categories.

We decided to bin the shows into three different genre categories: drama, comedy, and docuseries. Any show whose genre included the word *comedy*, *drama*, or *docuseries* was put into its respective category. From there, we were left with a large list of genres that we classified into the bins based on how we felt they best fit. For docuseries, we included any genre that was non-fiction or depicted real world events. This included true crime documentaries, reality competition shows, and game shows. For drama, we included any genre that was classified as a genre that is typically dramatic, such as horror, thriller, and telenovela. For comedy, we included any genre that is typically lighthearted, such as sitcoms, children’s shows, and mockumentary.

One important caveat: each show was classified as one of the three genre categories with only one exception. There is a small subset of shows in the dataset whose genre lists both Comedy and Drama, such as the show *The Bear*. *The Bear*’s genre was listed as ‘comedy drama’, and as such, it felt disingenuous to assign the show to a single bin. Therefore, if a show’s genre specifically had both of the words ‘comedy’ and ‘drama’, we classified the show as both a comedy and a drama. As we were essentially duplicating these shows, we separated the binned genres into a different table in our database so we don’t have duplicate shows in the shows table and can maintain having a single row for each show in our shows table.

We also gathered information on the language of the show. As mentioned above, we only collected the ratings for the US specifically, but as we know, the US is a melting pot of different cultures and backgrounds. This meant that there were a small, but not insignificant number of shows in our dataset whose dialogue is primarily in a foreign language. So we decided to also gather language data from Wikipedia while we were gathering the genre information.

## Data Ethics

Our study focuses on shows included in the top 10 lists by Nielsen and Netflix, providing insight into the most popular content rather than a comprehensive view of the entire streaming landscape. This approach acknowledges that the rankings may fluctuate based on the release of highly anticipated shows, which could overshadow other content that might otherwise gain attention in a different week.

We also recognize that subscription services come with inherent biases, as the audience demographic varies by platform, influenced by cost and accessibility. Streaming services, ranging from $5.99 (ad-supported Paramount+ or Peacock) to $15.99 (ad-free HBO Max) per month [@moses2023], are not universally accessible, potentially skewing our findings towards a more affluent or tech-savvy audience.

In considering the ethical dimensions of our research, we must consider the potential implications of our findings on the streaming industry. If our study concludes that the all-at-once release model generates more sustained buzz, this could influence platforms to favor this approach, potentially exacerbating binge-watching behavior. While convenient, binge-watching raises concerns about mental and physical health, such as increased screen time, sleep disruption, and the potential for addictive consumption patterns [@northwestern2024].

Furthermore, if streaming platforms were to prioritize all-at-once releases based on our findings, it could lead to unequal opportunities for content creators. Smaller or less mainstream shows might struggle to compete in a landscape where immediate, large-scale engagement becomes the standard measure of success.