# Conclusions

The question this project set out to answer was “*Does the release schedule of a show (weekly, in parts, or all at once) impact their staying power?*” We looked at multiple contributing factors, including genre and streaming platform. We found that there is a statistically significant difference in how long a show’s popularity is sustained based on the streaming platform, the genre, and the release schedule. We also found that the combination of release schedule and genre is statistically significant for a show’s popularity. Ultimately, we found that weekly releases are ideal for shows with preexisting fanbases, but are not ideal for newly released shows without a preexisting fanbase.

# References

Barnes, B. (2019, November 18). The streaming era has finally arrived. everything is about to change. *The New York Times*. <https://www.nytimes.com/2019/11/18/business/media/streaming-hollywood-revolution.html>

Hemingway, E. (n.d.). A quote by Ernest Hemingway. *Goodreads*. <https://www.goodreads.com/quotes/9556005-every-man-has-two-deaths-when-he-is-buried-in>  

McFarland, M. (2024, June 10). Dissecting the frustration and confusion of the "Bridgerton" split season. *Salon*. <https://www.salon.com/2024/06/10/bridgerton-split-season-3/> 

Molla, R. & Kafka, P. (2020, July 14). How Netflix made Breaking Bad a hit — and why that won’t happen again. *Vox*. <https://www.vox.com/recode/2020/7/14/21312595/netflix-breaking-bad-podcast-streaming-land-of-the-giants> 

Moses, C. (2023, December 29). What Your Favorite Streaming Services Will Cost You in 2024. *The New York Times*. <https://www.nytimes.com/2023/12/29/business/streaming-advertising-2024-netflix-amazon-prime.html> 

Nickinson, P. (2024, May 9). The 10 most popular streaming services, ranked by subscriber count. *Digital Trends*. <https://www.digitaltrends.com/home-theater/most-popular-streaming-services-by-subscribers/>

Press, J. (2021, May 14). One Episode at a Time, Please: Is a Binge Backlash Brewing? *Vanity Fair*. <https://www.vanityfair.com/hollywood/2021/05/tv-binge-vs-episode-by-episode-backlash> 

Rumble, T. (2018, July 18). 7 shows that helped make Netflix so popular. *BBC*. <https://www.bbc.com/news/entertainment-arts-44870538> 

Sutton, K. (2023, March 31). HBO’s Sunday night shows are more important than ever. *Marketing Brew*. <https://www.marketingbrew.com/stories/2023/03/31/hbo-s-sunday-night-shows-are-more-important-than-ever> 

Thomas, K. & Gennis, S. (2021, June 1). The great binge-watches of the streaming era. *Polygon*. <https://www.polygon.com/22417317/best-tv-shows-binge-watch> 
